version: "3.8"

services:
  configsvr:
    image: mongo:7
    container_name: config
    command: mongod --configsvr --replSet configReplSet --port 27018 --bind_ip_all
    ports:
      - "27018:27018"
    volumes:
      - config_data:/data/db

  shard1:
    image: mongo:7
    container_name: shard1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27019 --bind_ip_all
    ports:
      - "27019:27019"
    volumes:
      - shard1_data:/data/db

  shard2:
    image: mongo:7
    container_name: shard2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27020 --bind_ip_all
    ports:
      - "27020:27020"
    volumes:
      - shard2_data:/data/db

  shard3:
    image: mongo:7
    container_name: shard3
    command: mongod --shardsvr --replSet shard3ReplSet --port 27021 --bind_ip_all
    ports:
      - "27021:27021"
    volumes:
      - shard3_data:/data/db

  mongos:
    image: mongo:7
    container_name: mongos
    depends_on:
      - configsvr
      - shard1
      - shard2
      - shard3
    ports:
      - "27017:27017"
    command: mongos --configdb configReplSet/configsvr:27018 --port 27017 --bind_ip_all

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build: ./Worker
    container_name: worker
    depends_on:
      - mongos
      - rabbitmq

volumes:
  config_data:
  shard1_data:
  shard2_data:
  shard3_data:
