version: "3.8"

services:
  # --- MENSAGERIA ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  # --- APLICAÇÕES ---
  app_api:
    build: .                      
    container_name: api_vendas
    extra_hosts:
      - "mongos:98.92.68.72"
    ports:
      - "8000:8000"               
    depends_on:
      - rabbitmq                 
    environment:
      - RABBITMQ_HOST=rabbitmq  
      - MONGO_URL=mongodb://mongos:27017
      - SECRET_KEY=6dfbyg7HoXlu6McL1cqVBl1DYlVWfKhOQ7DlRR1WAI8
    volumes:
      - .:/app 

  worker:
    build: ./Worker
    container_name: worker
    command: python ./Worker/worker.py
    extra_hosts:
      - "mongos:98.92.68.72"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGO_URL=mongodb://mongos:27017
      - SECRET_KEY=6dfbyg7HoXlu6McL1cqVBl1DYlVWfKhOQ7DlRR1WAI8
    volumes:
      - .:/app
